apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: three-tier-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS names (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
